### PR TITLE
Allow to set imagePullSecrets

### PR DESCRIPTION
**Pull request by splattner**
This solves #12 

With this you can set imagePullSecrets for the Deployment.

Example values.yaml:

```
imagePullSecrets:
- name: mysecret
```

### CODE REVIEW

**Comment by splattner** [comment]
Anything else I need to do before you merge this?

**Comment by splattner** [comment]
Any chance to get this merged? Do I need to do anything more? Something missing?

**Comment by jmatute01** [comment]
Also interested to know if this is going to merged anytime soon?

**Review by debdutdeb — APPROVED** [review]
LGTM!

**Pull request merged**
